### ISSUE TITLE
레포 이름 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by benjioh5** [HYU-ICEWALL/Study_Network_Basic#1]
타 레포와 통일성을 위해 Study- 로 접두사 좀 바꿔주시면 안될까요? (아님 타 레포를 바꾸는 것도 한 방법이긴 합니다. 사실 _가 가독성이 좋긴하네요.)

**Comment by PineApple777** [comment]
@benjioh5 곧 바꾸겠습니다 : )

**Comment by benjioh5** [comment]
@PineApple777 넵!
